#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first:"
  echo "    https://github.com/mxcl/homebrew/wiki/installation"
  exit
else
  echo "  + Homebrew found."
fi

brew install zsh gpg
brew install grc coreutils
brew install ripgrep
brew install git
brew install wget
brew install curl
brew link curl --force
brew install git-extras
brew install vim
brew install hg
brew install tree jpeg libpng freetype
brew install automake autoconf openssl libyaml libxslt libtool unixodbc
brew install python python3 readline
brew install youtube-dl
pip install virtualenvwrapper

